import { StyleSheet } from 'react-native';
import {font, size} from '../../assets/utils/fonts';
import {color} from '../../assets/utils/colors';

export const CancelOrderStyles = StyleSheet.create({
    headerContainerWrap: {
        width: '100%',
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignContent: 'center',
        alignItems: 'center',
        flexWrap: 'wrap',
        gap: 5,
    },
    mainViewContainer: {
        width: '100%',
        flex: 1,
    },
    flexWrapRow: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    frameLeft: {
        width: 380,
        justifyContent: 'flex-start',
        alignItems: 'flex-start',
    },
    frameLeftInner: {
        width: '100%', 
        flex: 1,
    },
    frameRight: {
        flex: 1,
    },
    frameRightInner: {
        flex: 1,
        marginVertical: 20,
    },
    headerInfoWrap: {
        width: '100%',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignContent: 'center',
        alignItems: 'center',
        padding: 10,
        gap: 16,
    },
    headerInfoItem: {
        width: '32%',
        marginVertical: 5,
    },
    headerInfoItemData: {
        fontSize: size.normal,
        fontWeight: '600',
        color: color.light,
    },
    headerTitleWrap: {
        flexDirection: 'row',
        justifyContent: 'center',
        gap: 5,
    },
    headerTitleWrapInner: {
        flexDirection: 'row', 
        justifyContent: 'center'
    },
    headerTitle: {
        fontSize: size.h2,
        fontWeight: '600',
    },
    frameContainerWrap: {
        flexDirection: 'row',
        flex: 1,
        gap: 15,
        padding: 15,
        backgroundColor: color.light,
    },
    buttonsWrap: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 5,
        marginBottom: 5,
    },
    buttonFlex: {
      flex: 1,
      flexDirection: 'row',
      gap: 6,
    },
    buttonSecondary: {
      width: 130,
      height: 65,
      backgroundColor: color.secondary,
      borderRadius: 6,
      elevation: 4,
      color: '#000',
      display: 'flex',
      justifyContent: 'center',
      alignContent: 'center',
      alignItems: 'center',
    },
    buttonText: {
      fontSize: size.small,
      fontFamily: font.semibold,
      fontWeight: '700',
      color: color.light,
      textAlign: 'center',
      textTransform: 'uppercase',
    },
    orderSummaryTitle: {
        fontSize: size.h3,
        color: color.tertiary,
        fontFamily: font.regular,
        fontWeight: '700',
        marginTop: 10,
        marginBottom: 10,
        textAlign: 'center',
    },
    orderSummaryWrap: {
        width: '100%',
        padding: 10,
        gap: 16,
        elevation: 3,
        backgroundColor: color.light,
    },
    tblDisplayItem: {
        width: '100%',
        flexDirection: 'row',
        borderBottomWidth: 1,
        borderBottomColor: color.border,
    },
    tblDisplayItemNoBorder: {
        width: '100%',
        flexDirection: 'row',
    },
    tblDisplayCell: {
        flex: 1,
        paddingTop: 9,
        paddingBottom: 7,
        paddingHorizontal: 5,
        fontFamily: font.regular,
        fontSize: size.normal,
        color: color.text,
    },
    tblDisplayCellData: {
        fontFamily: font.regular,
        fontSize: size.normal,
        color: color.text,
    },
    tblDisplayCellPadding: {
        paddingLeft: 20,
    },
    tblDisplayCellSubData: {
        fontFamily: font.regular,
        fontSize: size.small,
        color: color.primary,
    },
    tblCellFlex2: {
      flex: 2,
    },
    subtotalWrap: {
        width: '100%',
        height: 50,
        padding: 6,
        gap: 16,
        elevation: 3,
        backgroundColor: color.info,
        marginBottom: 10,
    },
    tblCellFlex1: {
        flex: 1,
    },
    tblDisplayCellTotal: {
        flex: 1,
        paddingTop: 9,
        paddingBottom: 7,
        paddingHorizontal: 5,
        fontFamily: font.regular,
        fontSize: size.h3,
        color: color.text,
    },
    tblCellFlex8: {
        flex: 8,
    },
    defaultHeading: {
        backgroundColor: color.light,
        width: '100%',
        height: 45,
        justifyContent: 'center',
        paddingHorizontal: 10,
        borderBottomWidth: 4,
        borderBottomColor: color.border,
        marginBottom: 10,
    },
    defaultHeadingWrap: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    defaultHeadingText: {
        color: color.secondary,
        fontSize: size.h3,
        fontFamily: font.semibold,
        textTransform: 'uppercase',
        fontWeight: '700',
    },
    orderInfoContainer: {
        width: '100%',
        padding: 10,
        borderWidth: 1,
        borderColor: color.border,
        backgroundColor: color.light,
        marginBottom: 10,
    },
    orderInfoRow: {
        width: '100%',
        flexDirection: 'row',
        marginTop: 5,
    },
    cancelOrderSummaryWrap: {
        width: '100%',
        padding: 10,
        gap: 16,
        elevation: 3,
        backgroundColor: color.light,
    },
    cancelOrderNotesWrap: {
        width: '100%',
        padding: 10,
        gap: 16,
        elevation: 3,
        backgroundColor: color.light,
        marginVertical: 10,
    },
    textareaContainer: {
        height: 140,
        padding: 5,
        backgroundColor: color.background,
        borderWidth: 1,
        borderColor: color.border,
    },
    textarea: {
        textAlignVertical: 'top',  // hack android
        height: 140,
        fontSize: size.normal,
        padding: 10,
        color: color.dark,
    },
    notesText: {
        fontSize: size.normal,
        color: color.dark,
        marginVertical: 5,
    },
    textareaPlaceholder: {
        color: color.dark,
    },
    notesWrap: {
        width: '100%',
        paddingTop: 15,
        paddingRight: 15,
        paddingLeft: 15,
    },
    notesInfoWrap: {
        width: '100%',
        paddingBottom: 15,
        paddingRight: 15,
        paddingLeft: 15,
    },
    notesInfoTextsWrap: {
        marginHorizontal: 5,
    },
    notesInfoTexts: {
        fontSize: size.normal,
        color: color.dark,
        marginVertical: 5,
    },
    buttonsApplyWrap: {
        flexDirection: 'row',
        marginTop: 10,
        marginBottom: 10,
    },
    buttonsApplyText: {
        fontSize: size.h2,
        color: color.light,
        fontWeight: '700',
    },
    orderSummaryHeading: {
        backgroundColor: color.light,
        width: '100%',
        height: 40,
        justifyContent: 'center',
        paddingHorizontal: 10,
        borderBottomWidth: 2,
        borderBottomColor: color.border,
        marginTop: 10,
        marginBottom: 5,
    },
    orderSummaryHeadingWrap: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    orderSummaryHeadingText: {
        color: color.tertiary,
        fontSize: size.normal,
        fontFamily: font.semibold,
        textTransform: 'uppercase',
        fontWeight: '700',
    },
});