import { StyleSheet, Text, View } from 'react-native';

import {color} from '../../assets/utils/colors';
import {font, size} from '../../assets/utils/fonts';

export const ReprintReceiptStyles = StyleSheet.create({
    headerContainerWrap: {
        width: '100%',
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignContent: 'center',
        alignItems: 'center',
        flexWrap: 'wrap',
        gap: 5,
    },
    headerInfoWrap: {
        width: '100%',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignContent: 'center',
        alignItems: 'center',
        padding: 10,
        gap: 16,
    },
    headerInfoItem: {
        width: '32%',
        marginVertical: 5,
    },
    headerInfoItemData: {
        fontSize: size.normal,
        fontWeight: '600',
        color: color.light,
    },
    headerTitleWrap: {
        flexDirection: 'row',
        justifyContent: 'center',
        gap: 5,
    },
    headerTitleWrapInner: {
        flexDirection: 'row', 
        justifyContent: 'center'
    },
    headerTitle: {
        fontSize: size.h2,
        fontWeight: '600',
    },
    frameContainerWrap: {
        flexDirection: 'row',
        flex: 1,
        gap: 15,
        padding: 15,
        backgroundColor: color.light,
    },
    frameLeft: {
        width: 320,
        justifyContent: 'flex-start',
        alignItems: 'flex-start',
    },
    frameLeftInner: {
        width: '100%', 
        flex: 1,
    },
    buttonsWrap: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 5,
        marginBottom: 5,
    },
    buttonFlex: {
      flex: 1,
      flexDirection: 'row',
      gap: 6,
    },
    buttonSecondary: {
      width: 130,
      height: 65,
      backgroundColor: color.secondary,
      borderRadius: 6,
      elevation: 4,
      color: '#000',
      display: 'flex',
      justifyContent: 'center',
      alignContent: 'center',
      alignItems: 'center',
    },
    buttonText: {
      fontSize: size.small,
      fontFamily: font.semibold,
      fontWeight: '700',
      color: color.light,
      textAlign: 'center',
      textTransform: 'uppercase',
    },
    orderSummaryTitle: {
        fontSize: size.normal,
        color: color.primary,
        fontFamily: font.regular,
        fontWeight: '700',
        marginTop: 10,
    },
    orderSummaryWrap: {
        width: '100%',
        //height: 300,
        padding: 10,
        gap: 16,
        elevation: 3,
        backgroundColor: color.light,
    },
    subtotalWrap: {
        width: '100%',
        height: 50,
        padding: 6,
        gap: 16,
        elevation: 3,
        backgroundColor: color.info,
        marginBottom: 10,
    },
    orderInfoContainer: {
        width: '100%',
        padding: 10,
        borderWidth: 1,
        borderColor: color.border,
        backgroundColor: color.light,
        marginBottom: 10,
    },
    orderInfoRow: {
        width: '100%',
        flexDirection: 'row',
        marginTop: 5,
    },
    tblDisplayItem: {
        width: '100%',
        flexDirection: 'row',
        borderBottomWidth: 1,
        borderBottomColor: color.border,
    },
    tblDisplayCell: {
        flex: 1,
        paddingTop: 9,
        paddingBottom: 7,
        paddingHorizontal: 5,
        fontFamily: font.regular,
        fontSize: size.normal,
        color: color.text,
    },
    tblDisplayCellData: {
        fontFamily: font.regular,
        fontSize: size.normal,
        color: color.text,
    },
    tblDisplayCellPadding: {
        paddingLeft: 20,
    },
    tblDisplayCellSubData: {
        fontFamily: font.regular,
        fontSize: size.small,
        color: color.primary,
    },
    tblDisplayItemNoBorder: {
        width: '100%',
        flexDirection: 'row',
    },
    tblCellFlex1: {
        flex: 1,
    },
    tblCellFlex2: {
        flex: 2,
    },
    tblCellFlex3: {
        flex: 3,
    },
    tblCellFlex4: {
        flex: 4,
    },
    tblCellFlex5: {
        flex: 5,
    },
    tblCellFlex6: {
        flex: 6,
    },
    tblCellFlex7: {
        flex: 7,
    },
    tblCellFlex8: {
        flex: 8,
    },
    tblCellFlex9: {
        flex: 9,
    },
    tblCellFlex10: {
        flex: 10,
    },
    tblDisplayCellTotal: {
        flex: 1,
        paddingTop: 9,
        paddingBottom: 7,
        paddingHorizontal: 5,
        fontFamily: font.regular,
        fontSize: size.h3,
        color: color.text,
    },

    frameRight: {
        flex: 1,
    },
    frameRightInner: {
        flex: 1,
        marginBottom: 20,
    },
    defaultHeading: {
        backgroundColor: color.light,
        width: '100%',
        height: 45,
        justifyContent: 'center',
        paddingHorizontal: 10,
        borderBottomWidth: 4,
        borderBottomColor: color.border,
        marginBottom: 10,
    },
    defaultHeadingWrap: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    defaultHeadingText: {
        color: color.tertiary,
        fontSize: size.h3,
        fontFamily: font.semibold,
        textTransform: 'uppercase',
        fontWeight: '700',
    },
    searchInputText: {
        width: '100%',
        borderWidth: 1,
        borderColor: color.border,
        padding: 8,
        color: color.primary,
        fontSize: size.normal,
        backgroundColor: color.light,
    },
    contentSection: {
        width: '100%',
        height: 'auto',
        justifyContent: 'center',
        backgroundColor: color.light,
        paddingHorizontal: 20,
        paddingVertical: 20,
        borderBottomWidth: 4,
        borderBottomColor: color.border,
        marginBottom: 10,
    },
    searchBoxHeader: {
        width: '100%',
        height: 'auto',
        marginVertical: 5,
    },
    searchBoxHeaderText: {
        fontSize: size.h3,
        color: color.dark,
        fontWeight: '700'
    },
    searchBoxContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        gap: 40,
    },
    buttonFind: {
      width: 130,
      backgroundColor: color.secondary,
      borderRadius: 6,
      elevation: 4,
      color: '#000',
      display: 'flex',
      justifyContent: 'center',
      alignContent: 'center',
      alignItems: 'center',
      padding: 12,
    },
    buttonFindText: {
      fontSize: size.normal,
      fontFamily: font.semibold,
      fontWeight: '700',
      color: color.light,
      textAlign: 'center',
      textTransform: 'uppercase',
    },
    buttonReprint: {
      width: 200,
      backgroundColor: color.secondary,
      borderRadius: 6,
      elevation: 4,
      color: '#000',
      display: 'flex',
      justifyContent: 'center',
      alignContent: 'center',
      alignItems: 'center',
      padding: 16,
    },
    buttonReprintText: {
      fontSize: size.normal,
      fontFamily: font.semibold,
      fontWeight: '700',
      color: color.light,
      textAlign: 'center',
      textTransform: 'uppercase',
    },
    searchResultsContainer: {
        width: '100%',
        flex: 1,
    },
    searchResultsContainerInner: {
        width: '100%',
        padding: 10,
        gap: 16,
        elevation: 3,
        backgroundColor: color.light,
        marginVertical: 25,
    },
    tblDisplayCellLink: {
      color: color.link,
      textDecorationLine: 'underline',
      lineHeight: 20,
    },
    textareaContainer: {
        height: 140,
        padding: 5,
        backgroundColor: color.background,
        borderWidth: 1,
        borderColor: color.border,
    },
    textarea: {
        textAlignVertical: 'top',  // hack android
        height: 140,
        fontSize: size.normal,
        padding: 10,
        color: color.dark,
    },
    textareaPlaceholder: {
        color: color.dark,
    },
    orderSummaryHeading: {
        backgroundColor: color.light,
        width: '100%',
        height: 40,
        justifyContent: 'center',
        paddingHorizontal: 10,
        borderBottomWidth: 2,
        borderBottomColor: color.border,
        marginTop: 10,
        marginBottom: 5,
    },
    orderSummaryHeadingWrap: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    orderSummaryHeadingText: {
        color: color.tertiary,
        fontSize: size.normal,
        fontFamily: font.semibold,
        textTransform: 'uppercase',
        fontWeight: '700',
    },
});