import { StyleSheet } from 'react-native';
import {font, size} from '../../assets/utils/fonts';
import {color} from '../../assets/utils/colors';

export const AddOrderStyles = StyleSheet.create({
    frameContainerWrap: {
        flexDirection: 'row',
        flex: 1,
        gap: 15,
        padding: 15,
        backgroundColor: color.light,
    },
    headerContainerWrap: {
        width: '100%',
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignContent: 'center',
        alignItems: 'center',
        flexWrap: 'wrap',
        gap: 5,
    },
    mainViewContainer: {
        width: '100%',
        flex: 1,
    },
    frameLeft: {
        width: 380,
        justifyContent: 'flex-start',
        alignItems: 'flex-start',
    },
    frameLeftInner: {
        width: '100%', 
        flex: 1,
    },
    frameRight: {
        flex: 1,
    },
    frameRightInner: {
        flex: 1,
        marginVertical: 20,
    },
    headerInfoWrap: {
        width: '100%',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignContent: 'center',
        alignItems: 'center',
        padding: 10,
        gap: 16,
    },
    headerInfoItem: {
        width: '32%',
        marginVertical: 5,
    },
    headerInfoItemData: {
        fontSize: size.normal,
        fontWeight: '600',
        color: color.light,
    },
    headerTitleWrap: {
        flexDirection: 'row',
        justifyContent: 'center',
        gap: 5,
    },
    headerTitleWrapInner: {
        flexDirection: 'row', 
        justifyContent: 'center'
    },
    headerTitle: {
        fontSize: size.h2,
        fontWeight: '600',
    },
    orderSummaryWrap: {
        width: '100%',
        //height: 200,
        padding: 10,
        gap: 16,
        elevation: 3,
        backgroundColor: color.light,
    },
    orderSummaryTitle: {
        fontSize: size.normal,
        color: color.primary,
        fontFamily: font.regular,
        fontWeight: '700',
        marginTop: 10,
    },
    orderAdditionalWrap: {
        width: '100%',
        padding: 10,
        gap: 16,
        elevation: 3,
        backgroundColor: color.light,
    },
    subtotalWrap: {
        width: '100%',
        padding: 6,
        gap: 16,
        elevation: 3,
        backgroundColor: color.info,
        marginBottom: 10,
    },
    tblDisplayRows: {
        width: '100%',
        flex: 1,
    },
    tblDisplayItem: {
        width: '100%',
        flexDirection: 'row',
        borderBottomWidth: 1,
        borderBottomColor: color.border,
    },
    tblDisplayCell: {
        flex: 1,
        paddingTop: 9,
        paddingBottom: 7,
        paddingHorizontal: 5,
        color: color.text,
    },
    tblDisplayCellData: {
        fontFamily: font.regular,
        fontSize: size.normal,
        color: color.text,
    },
    tblDisplayCellSubData: {
        fontFamily: font.regular,
        fontSize: size.small,
        color: color.primary,
    },
    tblDisplayCellPadding: {
        paddingLeft: 20,
    },
    tblDisplayCellLink: {
        color: color.link,
        textDecorationLine: 'underline',
        lineHeight: 20,
    },
    tblCellFlex8: {
        flex: 8,
    },
    tblCellFlex4: {
        flex: 4,
    },
    tblCellFlex2: {
        flex: 2,
    },
    tblCellFlex1: {
        flex: 1,
    },
    tblCellFlex3: {
        flex: 3,
    },
    //Order Info
    OrderInfoContainer: {
        width: '100%',
        padding: 10,
        borderWidth: 1,
        borderColor: color.border,
        backgroundColor: color.light,
        marginBottom: 10,
    },
    orderInfoRow: {
        width: '100%',
        flexDirection: 'row',
        marginTop: 5,
    },
    button: {
        flex: 0,
        width: 80,
        height: 60,
        padding: 20,
        backgroundColor: color.primary,
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 6,
        shadowColor: color.dark,
        shadowOffset: {width: 0, height: 1},
        shadowOpacity: 0.8,
        shadowRadius: 2,
        elevation: 4,
    },
    buttonFlex: {
      flex: 1,
      flexDirection: 'row',
      gap: 6,
    },
    buttonSecondary: {
      width: '100%',
      height: 80,
      padding: 12,
      backgroundColor: color.secondary,
      borderRadius: 6,
      elevation: 4,
      color: '#000',
      display: 'flex',
      justifyContent: 'center',
      alignContent: 'center',
      alignItems: 'center',
    },
    buttonText: {
      fontSize: size.small,
      fontFamily: font.medium,
      color: color.light,
      textAlign: 'center',
      textTransform: 'uppercase',
    },
    tblDisplayCellTotal: {
        flex: 1,
        paddingTop: 9,
        paddingBottom: 7,
        paddingHorizontal: 5,
        fontFamily: font.regular,
        fontSize: size.h3,
        color: color.text,
    },
    buttonsWrap: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 5,
        marginBottom: 5,
    },
    productItemsContainer: {
        flex: 1,
        flexDirection: 'row',
        justifyContent: 'flex-start',
        alignContent: 'flex-start',
        alignItems: 'flex-start',
        flexWrap: 'wrap',
        gap: 15,
    },
    productItem: {
        width: 200,
        height: 200,
        gap: 5,
        backgroundColor: color.light,
        borderRadius: 10,
        padding: 10,
        flexDirection: 'column',
        alignContent: 'center',
        alignItems: 'center',
    },
    productImg: {
        textAlign: 'center',
    },
    productName: {
        fontSize: size.normal,
        fontWeight: '600',
        color: color.dark,
        textAlign: 'center',
    },
    inputContainer: {
        backgroundColor: color.background,
        flexDirection: 'row',
        alignItems: 'center',
        borderRadius: 20,
        elevation: 10,
        gap: 5,
        marginVertical: 10,
    },
    inputText: {
        width: 50,
        padding: 5,
        fontSize: size.normal,
        textAlign: 'center',
    },
    priceQtyWrap: {
        flexDirection: 'row',
        alignContent: 'center',
        alignItems: 'center',
        gap: 25,
        justifyContent: 'space-between',
        width: '100%',
    },
    productItemPrice: {
        fontSize: size.normal,
        fontWeight: '600',
        color: color.dark,
        textAlign: 'center',
    },
    productItemName: {
        fontSize: size.small,
        fontWeight: '500',
        color: color.dark,
        textAlign: 'center',
    },
    tabIndicator: {
        backgroundColor: color.secondary,
    },
    tabItem: {
        backgroundColor: color.tertiary,
    },
    tabItemLabel: {
        fontSize: size.normal,
        fontWeight: '700',
    },
    orderSummaryHeading: {
        backgroundColor: color.light,
        width: '100%',
        height: 40,
        justifyContent: 'center',
        paddingHorizontal: 10,
        borderBottomWidth: 2,
        borderBottomColor: color.border,
        marginTop: 10,
        marginBottom: 5,
    },
    orderSummaryHeadingWrap: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    orderSummaryHeadingText: {
        color: color.tertiary,
        fontSize: size.normal,
        fontFamily: font.semibold,
        textTransform: 'uppercase',
        fontWeight: '700',
    },
    tblDisplayItemNoBorder: {
        width: '100%',
        flexDirection: 'row',
    },
    productMenuIndicator: {
        backgroundColor: color.tertiary,
        color: color.light,
    },
    productListScroll: {
        width: '100%',
        flex: 1,
    },
    productList: {
        flex: 1,
        flexDirection: 'row',
        gap: 15,
        alignItems: 'flex-start',
        justifyContent: 'flex-start',
        flexWrap: 'wrap',
        marginVertical: 10,
        marginHorizontal: 10,
    },
});