import { StyleSheet } from 'react-native';
import {font, size} from '../../assets/utils/fonts';
import {color} from '../../assets/utils/colors';

export const PayOrderStyles = StyleSheet.create({
    frameContainerWrap: {
        flexDirection: 'row',
        flex: 1,
        gap: 15,
        padding: 15,
        backgroundColor: color.light,
    },
    headerContainerWrap: {
        width: '100%',
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignContent: 'center',
        alignItems: 'center',
        flexWrap: 'wrap',
        gap: 5,
    },
    mainViewContainer: {
        width: '100%',
        flex: 1,
    },
    frameLeft: {
        width: 320,
        justifyContent: 'flex-start',
        alignItems: 'flex-start',
    },
    frameLeftInner: {
        width: '100%', 
        flex: 1,
    },
    frameRight: {
        flex: 1,
    },
    frameRightInner: {
        flex: 1,
        marginBottom: 20,
    },
    headerInfoWrap: {
        width: '100%',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignContent: 'center',
        alignItems: 'center',
        padding: 10,
        gap: 16,
    },
    headerInfoItem: {
        width: '32%',
        marginVertical: 5,
    },
    headerInfoItemData: {
        fontSize: size.normal,
        fontWeight: '600',
        color: color.light,
    },
    headerTitleWrap: {
        flexDirection: 'row',
        justifyContent: 'center',
        gap: 5,
    },
    headerTitleWrapInner: {
        flexDirection: 'row', 
        justifyContent: 'center'
    },
    headerTitle: {
        fontSize: size.h2,
        fontWeight: '600',
    },
    orderSummaryWrap: {
        width: '100%',
        //height: 300,
        padding: 10,
        gap: 16,
        elevation: 3,
        backgroundColor: color.light,
    },
    orderSummaryTitle: {
        fontSize: size.normal,
        color: color.primary,
        fontFamily: font.regular,
        fontWeight: '700',
        marginTop: 10,
    },
    subtotalWrap: {
        width: '100%',
        height: 50,
        padding: 6,
        gap: 16,
        elevation: 3,
        backgroundColor: color.info,
        marginBottom: 10,
    },
    tblDisplayCellData: {
        fontFamily: font.regular,
        fontSize: size.normal,
        color: color.text,
    },
    tblDisplayCellSubData: {
        fontFamily: font.regular,
        fontSize: size.small,
        color: color.primary,
    },
    tblDisplayCellPadding: {
        paddingLeft: 20,
    },
    tblCellFlex8: {
        flex: 8,
    },
    tblCellFlex4: {
        flex: 4,
    },
    tblCellFlex2: {
        flex: 2,
    },
    tblCellFlex1: {
        flex: 1,
    },
    //Order Info
    orderInfoContainer: {
        width: '100%',
        padding: 10,
        borderWidth: 1,
        borderColor: color.border,
        backgroundColor: color.light,
        marginBottom: 10,
    },
    orderInfoRow: {
        width: '100%',
        flexDirection: 'row',
        marginTop: 5,
    },
    button: {
        flex: 0,
        width: 80,
        height: 60,
        padding: 20,
        backgroundColor: color.primary,
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 6,
        shadowColor: color.dark,
        shadowOffset: {width: 0, height: 1},
        shadowOpacity: 0.8,
        shadowRadius: 2,
        elevation: 4,
    },
    buttonFlex: {
      flex: 1,
      flexDirection: 'row',
      gap: 6,
    },
    buttonSecondary: {
      width: 130,
      height: 65,
      backgroundColor: color.secondary,
      borderRadius: 6,
      elevation: 4,
      color: '#000',
      display: 'flex',
      justifyContent: 'center',
      alignContent: 'center',
      alignItems: 'center',
    },
    buttonText: {
      fontFamily: font.semibold,
      fontWeight: '700',
      color: color.light,
      textAlign: 'center',
      textTransform: 'uppercase',
    },
    //Data Table Display
    tblDisplayRows: {
        flex: 1,
    },
    tblDisplayItem: {
        width: '100%',
        flexDirection: 'row',
        borderBottomWidth: 1,
        borderBottomColor: color.border,
    },
    tblDisplayItemNoBorder: {
        width: '100%',
        flexDirection: 'row',
    },
    tblDisplayCell: {
        flex: 1,
        paddingTop: 9,
        paddingBottom: 7,
        paddingHorizontal: 5,
        fontFamily: font.regular,
        fontSize: size.normal,
        color: color.text,
    },
    tblDisplayCellLink: {
        color: color.link,
        textDecorationLine: 'underline',
        lineHeight: 20,
    },
    tblDisplayCellTotal: {
        flex: 1,
        paddingTop: 9,
        paddingBottom: 7,
        paddingHorizontal: 5,
        fontFamily: font.regular,
        fontSize: size.h3,
        color: color.text,
    },
    buttonsWrap: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 5,
        marginBottom: 5,
    },
    buttonsOrdersTransactWrap: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 5,
        marginBottom: 5,
    },
    productItemsContainer: {
        flex: 1,
        flexDirection: 'row',
        justifyContent: 'flex-start',
        alignContent: 'flex-start',
        alignItems: 'flex-start',
        flexWrap: 'wrap',
        gap: 15,
    },
    productItem: {
        width: 200,
        height: 200,
        gap: 5,
        backgroundColor: color.light,
        borderRadius: 10,
        padding: 10,
        flexDirection: 'column',
        alignContent: 'center',
        alignItems: 'center',
    },
    productImg: {
        textAlign: 'center',
    },
    productName: {
        fontSize: size.normal,
        fontWeight: '600',
        color: color.dark,
        textAlign: 'center',
    },
    inputContainer: {
        backgroundColor: color.background,
        flexDirection: 'row',
        alignItems: 'center',
        borderRadius: 20,
        elevation: 10,
        gap: 5,
        marginVertical: 10,
    },
    inputText: {
        width: 50,
        padding: 5,
        fontSize: size.normal,
        textAlign: 'center',
    },
    priceQtyWrap: {
        flexDirection: 'row',
        alignContent: 'center',
        alignItems: 'center',
        gap: 25,
    },
    productItemPrice: {
        fontSize: size.normal,
        fontWeight: '600',
        color: color.dark,
        textAlign: 'center',
    },
    productItemName: {
        fontSize: size.small,
        fontWeight: '500',
        color: color.dark,
        textAlign: 'center',
    },
    defaultHeading: {
        backgroundColor: color.light,
        width: '100%',
        height: 45,
        justifyContent: 'center',
        paddingHorizontal: 10,
        borderBottomWidth: 4,
        borderBottomColor: color.border,
        marginBottom: 10,
    },
    defaultHeadingWrap: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    defaultHeadingText: {
        color: color.tertiary,
        fontSize: size.h3,
        fontFamily: font.semibold,
        textTransform: 'uppercase',
        fontWeight: '700',
    },
    transactSection: {
        width: '100%',
        height: 'auto',
        justifyContent: 'center',
        backgroundColor: color.light,
        paddingHorizontal: 10,
        borderBottomWidth: 4,
        borderBottomColor: color.border,
        marginBottom: 10,
    },
    transactAddInfo: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        borderBottomWidth: 2,
        borderBottomColor: color.border,
        padding: 10,
        marginVertical: 20,
    },
    paymentOrderText: {
        fontFamily: font.semibold,
        fontSize: size.normal,
        color: color.secondary,
    },
    cashierText: {
        fontFamily: font.semibold,
        fontSize: size.normal,
        color: color.secondary,
        fontWeight: '700',
    },
    transactBody: {
        flexDirection: 'row',
        padding: 10,
    },
    transactLeft: {
        flex: 9,
    },
    paymentMethodItem: {
        width: '100%'
    },
    transactTextData: {
        fontSize: size.h3,
        color: color.dark,
    },
    transactText: {
        fontSize: size.h2,
        color: color.secondary,
        fontWeight: '700',
    },
    modePaymentData: {
        fontSize: size.h3,
        color: color.dark,
    },
    modePaymentText: {
        fontFamily: font.bold,
        fontSize: size.h2,
        color: color.secondary,
        marginVertical: 10,
        fontWeight: '700',
        textTransform: 'uppercase',
    },
    transactRight: {
        flex: 3,
    },
    transactNoWrap: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    modePaymentSelection: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    orderTransactItemName: {
        flex: 4,
    },
    orderTransactItemData: {
        flex: 8,
    },
    orderTransactItem: {
        fontSize: size.h3,
        color: color.dark,
    },
    transactInputText: {
        width: '95%',
        borderWidth: 1,
        borderColor: color.dark,
        paddingTop: 15,
        paddingBottom: 15,
        paddingLeft: 8, 
        paddingRight: 8,
        color: color.primary,
        fontWeight: '700',
        fontSize: size.h3,
        textAlign: 'right',
        backgroundColor: color.light,
    },
    subTotalTransactWrap: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    serviceChargeWrap: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    totalWrap: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    cashWrap: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    changeWrap: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    tblDisplayTransactItem: {
        width: '100%',
        padding: 10,
    },
    transactItemsWrap: {
        marginVertical: 6,
    },
    transactOrdersWrap: {
        width: '100%',
        height: 'auto',
        padding: 6,
        marginBottom: 10,
    },
    transactButtonText: {
        fontSize: size.normal,
        fontFamily: font.semibold,
        fontWeight: '700',
        color: color.light,
        textAlign: 'center',
        textTransform: 'uppercase',
    },
    buttonPaymentSelection: {
        backgroundColor: color.custom.purple,
        borderRadius: 6,
        elevation: 4,
        color: '#000',
        marginLeft: 10,
        padding: 5,
    },
    buttonPaymentChoices: {
        backgroundColor: color.custom.purple,
        flex: 0,
        width: 110,
        height: 90,
        padding: 5,
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 6,
        shadowColor: color.dark,
        shadowOffset: {width: 0, height: 1},
        shadowOpacity: 0.8,
        shadowRadius: 2,
        elevation: 4,
      },
      buttonPaymentChoicesText: {
        fontSize: size.h3,
        fontFamily: font.semibold,
        fontWeight: '600',
        color: color.light,
        textAlign: 'center',
        textTransform: 'uppercase',
      },
   // modal
    centeredView: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 5,
        fontFamily: font.regular,
    },
    modalView: {
        backgroundColor: color.light,
        borderRadius: 10,
        borderWidth: 2,
        borderColor: color.tertiary,
        padding: 35,
        //alignItems: 'center',
        shadowColor: color.shadow,
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.5,
        shadowRadius: 4,
        elevation: 15,
    },
    // button: {
    //     borderRadius: 10,
    //     padding: 10,
    //     elevation: 2,
    // },
    buttonAccess: {
        width: 120,
        height: 40,
        backgroundColor: color.success,
        marginHorizontal: 10,
        marginVertical: 10,
        borderRadius: 10,
        gap: 2,
        elevation: 5,
    },
    buttonClose: {
        backgroundColor: color.alert,
        width: 120,
        height: 40,
        marginHorizontal: 10,
        marginVertical: 10,
        borderRadius: 10,
        gap: 2,
        elevation: 5,
    },
    textStyle: {
        color: color.light,
        fontWeight: 'bold',
        textAlign: 'center',
        fontSize: size.normal,
        fontFamily: font.regular,
    },
    modalTextHeading: {
        marginBottom: 15,
        textAlign: 'center',
        fontSize: size.h1,
        fontWeight: '600',
        color: color.dark,
        fontFamily: font.regular,
        textTransform: 'uppercase'
    },
    modalText: {
        marginBottom: 15,
        textAlign: 'center',
        fontSize: size.normal,
        fontWeight: '400',
        color: color.alert,
        fontFamily: font.regular,
    },
    discountsWrap: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 5,
    },
    discountsCodeWrap: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 5,
    },
    discountsText: {
        fontSize: size.h3,
        color: color.dark,
        fontWeight: '700',
    },
    discountsTextVal: {
        fontSize: size.h2,
        color: color.secondary,
    },
    codeText: {
        fontSize: size.h3,
        color: color.dark,
    },
    codeTextVal: {
        fontSize: size.h2,
        color: color.secondary,
    },
    discountsTypeWrap: {
        width: '100%',
        flexDirection: 'row',
        justifyContent: 'flex-start', 
        alignItems: 'flex-start',
        marginVertical: 20,
    },
    radioGroupWrap: {
        alignContent: 'flex-start',

    },
    radioText: {
        color: color.tertiary, 
        fontSize: size.h3
    },
    typesPercentWrap: {
        flexDirection: 'row',
        justifyContent: 'flex-start', 
        marginVertical: 10,
    },
    typesPercentText: {
        fontSize: size.normal,
        color: color.dark,
        fontWeight: '700',
    },
    typesPercentTextVal: {
        fontSize: size.normal,
        color: color.secondary,
    },
    borderBottom: {
        width: '100%',
        backgroundColor: color.light,
        paddingHorizontal: 10,
        paddingVertical: 10,
        borderBottomWidth: 3,
        borderBottomColor: color.border,
        marginBottom: 10,
    },
    borderTop: {
        width: '100%',
        backgroundColor: color.light,
        paddingHorizontal: 10,
        paddingVertical: 10,
        borderTopWidth: 3,
        borderTopColor: color.border,
        marginBottom: 10,
    },
    flexWrapRow: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    flexWrapCol: {
        flexDirection: 'column',
    },
    discountsModalView: {
        width: 600,
        backgroundColor: color.light,
        borderRadius: 10,
        borderWidth: 2,
        borderColor: color.tertiary,
        padding: 35,
        shadowColor: color.shadow,
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.5,
        shadowRadius: 4,
        elevation: 15,
    },
    discountsModalInputText: {
        width: '65%',
        borderWidth: 1,
        borderColor: color.border,
        paddingTop: 5,
        paddingBottom: 5,
        paddingLeft: 8, 
        paddingRight: 8,
        color: color.primary,
        fontWeight: '700',
        fontSize: size.h3,
        textAlign: 'right',
        backgroundColor: color.background,
    },
    discountCustomerInfo: {
        gap: 20,
    },
    discountCustomerInfoText: {
        width: '35%',
        fontSize: size.normal,
        color: color.dark,
    },
    buttonsApplyWrap: {
        flexDirection: 'row',
        marginTop: 45,
        marginBottom: 15,
    },
    buttonsApplyText: {
        fontSize: size.h2,
        color: color.light,
        fontWeight: '700',
    },
    //Split Payments
    splitPaymentsModalView: {
        width: 680,
        backgroundColor: color.light,
        borderRadius: 6,
        borderWidth: 2,
        borderColor: color.tertiary,
        padding: 35,
        shadowColor: color.shadow,
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.5,
        shadowRadius: 4,
        elevation: 15,
    },
    splitPaymentsTitleText: {
        fontSize: size.h3,
        color: color.dark,
    },
    buttonsApplySplitPaymentsWrap: {
        flexDirection: 'row',
        marginTop: 10,
        marginBottom: 45,
    },
    applySplitPaymentInputText: {
        borderWidth: 1,
        borderColor: color.border,
        paddingTop: 5,
        paddingBottom: 5,
        paddingLeft: 8, 
        paddingRight: 8,
        color: color.primary,
        fontWeight: '700',
        fontSize: size.h3,
        textAlign: 'right',
        backgroundColor: color.background,
    },
    applySplitPaymentItemName: {
        flex: 6,
    },
    applySplitPaymentItemData: {
        flex: 6,
    },
    orderSummaryHeading: {
        backgroundColor: color.light,
        width: '100%',
        height: 40,
        justifyContent: 'center',
        paddingHorizontal: 10,
        borderBottomWidth: 2,
        borderBottomColor: color.border,
        marginTop: 10,
        marginBottom: 5,
    },
    orderSummaryHeadingWrap: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    orderSummaryHeadingText: {
        color: color.tertiary,
        fontSize: size.normal,
        fontFamily: font.semibold,
        textTransform: 'uppercase',
        fontWeight: '700',
    },
    buttonConfirm: {
        width: 430,
        height: 70,
        backgroundColor: color.secondary,
        margin: 'auto',
        padding: 10,
        flexDirection: 'row',
        alignItems: 'center',
        alignContent: 'center',
        justifyContent: 'center',
        gap: 10,
        borderRadius: 4,
    },
    buttonMoreText: {
      margin: 0,
      fontSize: size.h3,
      color: color.light,
    },
    amountTenderedText: {
        width: '100%',
        borderWidth: 1,
        borderColor: color.dark,
        padding: 8,
        color: color.primary,
        fontSize: size.h3,
        backgroundColor: color.light,
        borderRadius: 5,
    },
});